### ISSUE TITLE
Release hangs with unhandled promise rejection warning

### ISSUE THREAD

**Issue by dcalhoun** [zeit/release#108]
Attempting to create release throws `UnhandledPromiseRejectionWarning`.

I'm not too sure what led to this state. I am attempted to create a release on a project I just updated. I remember doing the following:

### Steps
1. Attempted to create a release without bumping `package.json` version.
1. Bump `package.json` version with `release patch`.
1. Committed bump and pushed.
1. Created tag and pushed.
1. Marked first of several commits as "Ignore."

### Result
Release threw the `UnhandledPromiseRejectionWarning`.

### Environment
- macOS 10.13
- node 8.8.1
- release 2.5.2 (At the time of first error I was using a 1.x.x release, but then upgraded with no change.)

```bash
❯ release
✔ Checking if release already exists
✔ Loading commit history
! Please enter the type of change for each commit:

(node:61937) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: You must provide a `message` parameter
(node:61937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![release-promise-error](https://user-images.githubusercontent.com/438664/32134769-c264fbe2-bbb9-11e7-9e51-8a4098f64479.png)

**Comment by rauchg** [comment]
Just hit this. We're looking into it!
