### ISSUE TITLE
Add references to usernames that took part in PRs

### ISSUE THREAD

**Issue by leo** [zeit/release#11]

**Comment by hemanth** [comment]
Just noticed it assigned to you, have you started working on this? I was interested in pawing at this.

**Comment by leo** [comment]
@hemanth Give it a try! The solution would be to take the issue and PR ids out of the commit titles, download their meta data from GitHub's API and then add them all to a huge array so that we can show them at the end of the changelog in a "Credits" section.

If there aren't any PRs or issues linked in any of the commits, the array will be empty and the "Credits" section needs to be hidden.

**Comment by hemanth** [comment]
Cool, I was thinking of parsing commits between the latest commit and the latest tag commit and extract the info from it, we would be needed GitHub API for sure, there are few module out there which will get the list of contributors, but this issue is more specific.

**Comment by leo** [comment]
Added in [1.1.0](https://github.com/zeit/release/releases/tag/1.1.0)!

**Comment by hemanth** [comment]
Nice to see all the dogfooding and avoidance of unnecessary deps!
