### ISSUE TITLE
Stuck on "Opening GitHub authentication page"

### ISSUE THREAD

**Issue by styfle** [zeit/release#151]
## Steps to reproduce

1. Create private repo
2. Make a change in the repo and commit it
3. Install latest release `npm install -g release@6.0.0`
4. Run `release patch`

The browser does open and says it can be closed but it does not proceed and no Release is created (however the tag is there).

```
✔ Bumped version tag to 0.0.4
✔ Created release commit
✔ Tagged commit
✔ Pushed everything to remote
⠇ Opening GitHub authentication page
```

## Workaround

The workaround was to use `release patch --show-url` and then copy/paste that URL in the browser.

## Notes

This was originally reported by @bukinoshita in [a comment](https://github.com/zeit/release/issues/147#issuecomment-454948277).

**Comment by ijjk** [comment]
@styfle I just pushed up a PR addressing this issue, if you have a chance could you try out that version and see if the issue is resolved? You can try out the branch with:

```sh
git clone https://github.com/ijjk/release
cd release
git checkout fix-stall-on-open  
yarn install
yarn link
```

**Comment by styfle** [comment]
@ijjk That worked for me, thanks!

https://github.com/zeit/tracing-js/releases/tag/0.0.3
