### ISSUE TITLE
Branch Needs to be Up-to-date

### ISSUE THREAD

**Issue by casesandberg** [zeit/release#18]
My repo is up to date with origin and on master:
```sh
parzival:react-color case$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
parzival:react-color case$ release
Error! Your branch needs to be up-to-date with origin.
```

**Comment by leo** [comment]
I'm using [git-state](https://github.com/watson/git-state). Do you have any dirty files or stashes in there, maybe?

**Comment by casesandberg** [comment]
`git stash clear` fixed it.

**Comment by leo** [comment]
76925dfeef6b30ccc5b60488d5390483b75d1fe8

**Comment by niftylettuce** [comment]
Please re-open, this is still an issue.  I have a forked repo with this error.
