### ISSUE TITLE
Couldn't check if release exists

### ISSUE THREAD

**Issue by RijkvanZanten** [zeit/release#20]
I'm getting this error `Error! Couldn't check if release exists.` when trying to use `release` or access the options with `release -h`. What would cause this error? Are there any logs somewhere?

Using Node v7.2.1 on Mac OS 10.12.2

**Comment by leo** [comment]
It's trying to get the list of releases [here](https://github.com/zeit/release/blob/1fac7d2f99e3570183912759eceabfaf2e0237d2/bin/release.js#L212)... 🤔

**Comment by jamo** [comment]
This might have fixed the issue: https://github.com/zeit/release/commit/355eb22bc75ccc0abe6495f9ee6824cf5c9f2ce3

**Comment by leo** [comment]
@RijkvanZanten Please try [1.0.6](https://github.com/zeit/release/releases/tag/1.0.6)!

**Comment by ChopperLee2011** [comment]
I have the same problem, after success running `git push --tags`, the release still return this message:
Error! Couldn't check if release exists.
And my node version is 7.4.0 and release version is 1.1.7. Anyone can help me?

**Comment by leo** [comment]
@ChopperLee2011 Click on "Release" [here](https://github.com/settings/applications) and check if the app has enough perms to access the org that contains your repo.

**Comment by ChopperLee2011** [comment]
it should have rights, 'cause the push tags command works and the tag is already created in the repo, but `release` return error

**Comment by ChopperLee2011** [comment]
@leo ah, I find the repo is in a private org and release do not have right yet. so... 
thanks.
