### ISSUE TITLE
Shows incorrect commits

### ISSUE THREAD

**Issue by tleunen** [zeit/release#22]
I wanted to try `release` to make the next release for one of my project [pixi-multistyle-text](https://github.com/tleunen/pixi-multistyle-text) whish is currently 0.4.0. But when running it, it shows commits before that release, instead of showing only commits after that.

Here's what I get:
```bash
~/d/pixi-multistyle-text master ❯ release
✔ Checking if release already exists
✔ Loading commit history
! Please enter the type of change for each commit:

? chore: Remove gruntfile + new readme image (Use arrow keys)
❯ Minor Change (backwards-compatible functionality) 
  Patch (backwards-compatible bug fix) 
  ──────────────
  Ignore 
```

But as shown in the [history](https://github.com/tleunen/pixi-multistyle-text/commits/master), the commit is from Nov 5, 2016 and between 0.3.0 and 0.4.0, not after 0.4.0.

**Comment by leo** [comment]
What's the result of `git tag`? The package is using the tags to determine where to start and end looking for commits.

**Comment by tleunen** [comment]
`git tag` returns the entire list of tags, from 0.1.0 to 0.4.0.
```
v0.1.0
v0.1.1
v0.2.0
v0.2.1
v0.2.2
v0.3.0
v0.4.0
```

Is there any verbose mode to be able to better understand what it's doing?

**Comment by leo** [comment]
It looks like you haven't created a tag after `0.4.0`. In turn, the package expects that `0.4.0` is the latest tag (which it is) and therefore the tag for which you want to do a release...

**Comment by tleunen** [comment]
Oh I see.. So `release` doesn't create the new tag. This is something the user has to do. Any reason to that?

I would have thought `release` was meant to do a full release of a package (tagging + publishing + release notes), not just the release note part.

**Comment by leo** [comment]
@tleunen No. 😊 Like the repo description and README.md state it, it's meant to be used for:

> Manage GitHub Releases from the command line

and in README.md:

> When run, this command line interface automatically generates a new GitHub Release and populates it with the changes (commits) made since the last release.
