### ISSUE TITLE
Release fails if there are existing stashes

### ISSUE THREAD

**Issue by CaryLandholt** [zeit/release#23]
Receive `Error! Your branch needs to be up-to-date with origin.` when there are stashes.

It is failing when iterating through the `git-state` results.
https://github.com/zeit/release/blob/master/lib/repo.js#L48

Recommend this check be excluded from the failure check.

**Comment by leo** [comment]
We're actually [ignoring](https://github.com/zeit/release/blob/master/lib/repo.js#L28) stashes... 🤔
