### ISSUE TITLE
node: bad option: --harmony-async-await

### ISSUE THREAD

**Issue by oren** [zeit/release#24]
running `release` shows
```
node: bad option: --harmony-async-await
```

## More Info
node -v
```
v6.9.1
```

npm -v
```
3.10.8
```

cat /etc/lsb-release
```
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

**Comment by tleunen** [comment]
Release only works with Node >= 7. See https://github.com/zeit/release/blob/master/package.json#L36

**Comment by oren** [comment]
works now. thank you!
