### ISSUE TITLE
Opening authentication page does not work on Bash @ Windows

### ISSUE THREAD

**Issue by DoNormal** [zeit/release#26]
When running `release` it tries to open the GitHub authentication page, but the only thing I see is a flickering console message.

```
robert@HODOR:/mnt/c/Users/robert/Documents/GitHub/release-test$ release
⠼ Opening GitHub authentication page...
```

Running Bash on Windows Version 10.0.14393 Build 14393, node version 7.3.0. Happy to supply more info if needed 😃

**Comment by leo** [comment]
@DoNormal Is it still not working with the latest version?

**Comment by DoNormal** [comment]
I updated to 1.1.2, but the problem still occurs. Do you need me to provide more information, e.g. logs?

**Comment by leo** [comment]
Should work now!
