### ISSUE TITLE
Use Bluebird

### ISSUE THREAD

**Issue by lukeed** [zeit/release#28]
...unless this project is specifically a test case for native `async`/`await`.

Bluebird's implementations are still faster & more memory efficient than Node v7's version. Relying on Bluebird would also open the door to more Node versions.

**Comment by leo** [comment]
Thanks for your effort in creating this issue!

> ...unless this project is specifically a test case for native `async`/`await`.

But this is correct. I want to help the node/v8 community find and fix bugs in the native implementation of async/await. Also it makes the project's structure much clear! We're already transpiling most of our other packages and I noticed it creates a lot of overhead.

**Comment by lukeed** [comment]
> I want to help the node/v8 community find and fix bugs in the native implementation of async/await.

I can get behind that! :)

(There wouldn't be any compilation steps fyi; could run as it.)
