### ISSUE TITLE
FR: exit for node version is <7

### ISSUE THREAD

**Issue by hemanth** [zeit/release#31]
It would be useful to message the user and exit in case of node version mismatch?

Something like: 

```js
const semver = require('semver')

// Check if the current version of node is >=7
if(!semver.satisfies(process.version, '>=7.0.0')) {
  console.log('Please use node version >=7, needed for `--harmony-async-await` flag.')
}
```

**Comment by leo** [comment]
@hemanth without that node version, it will probably just break while it's parsing the code (before it will even reach the execution of the code you mentioned above)?

**Comment by hemanth** [comment]
We could have this as a `preinstall` script in `package.json` so that it wont hit the interpretive line that would bomb. @leo

**Comment by hemanth** [comment]
grrr, I was doing a `npm install check-node-version && check-node-version -q --node '~7' || echo "This package requires at least node v7. Please upgrade!'"`  @leo :P

**Comment by leo** [comment]
That also seems to be a great way to handle it! Pretty long command though, so it won't fit into the `scripts` property and still look good.

**Comment by hemanth** [comment]
Yup, `process.version[1]` is a very neat way of doing it indeed! 👍
