### ISSUE TITLE
CLI hangs after GitHub auth

### ISSUE THREAD

**Issue by zeke** [zeit/release#33]
:wave: This is a great project! I'm looking forward to using this on numerous projects.

I hit a few snags setting it up:

1. I came back to my terminal after authenticating in the browser.
1. The `Opening GitHub authentication page...` message remained on the screen for several seconds.
1. I hit 'Enter' a few times.
1. Eventually the GitHub step completed.
1. My previous `Enter` keystrokes were buffered and used as input to answer the patch/minor/major question(s).

<img width="614" alt="screen shot 2017-01-06 at 10 43 23 pm" src="https://cloud.githubusercontent.com/assets/2289/21740056/dfc95466-d461-11e6-80ed-2dae186df616.png">

A quick fix might be to lower this sleep value to something like 100ms. https://github.com/zeit/release/blob/d977a4a6c9878e643fa7fc43d959b8b77be14631/lib/connect.js#L107

**Comment by leo** [comment]
Thanks!
