### ISSUE TITLE
Use npm version tag for the release draft tag version 

### ISSUE THREAD

**Issue by dinoboff** [zeit/release#35]
Using v1.1.0, `release` create a draft targeting tag "x.x.x" instead of "vx.x.x". It would then create a tag from master instead of using the tag created by `npm version`.

### Steps

```
npm version patch
git push origin master vx.x.x
release
```

### Result

Open browser to a release draft with the "Tag version" field set "x.x.x" and an empty "Release title" field.

### Expected

It should create draft release with "Tag version" set to "vx.x.x" and "Release title" set to "x.x.x"

**Comment by dinoboff** [comment]
I notices `release` project own tags do not follow `npm version` convention. Would it be possible to have a flag to the set tag name format?

I don't mind which convention `release` use by default as long as it's compatible with `npm version` tags.

**Comment by aesopwolf** [comment]
It actually **shouldn't** create draft release with "Tag version" set to "vx.x.x"

> The version tag should not include the "v" prefix. 

- https://github.com/zeit/release/pull/30#issuecomment-270598773

I learned this after opening a PR to add it haha

**Comment by dinoboff** [comment]
Oops, I think I only scanned closed issues for `npm version`
