### ISSUE TITLE
Support for custom middleware

### ISSUE THREAD

**Issue by leo** [zeit/release#38]
[Tweet](https://twitter.com/notquiteleo/status/817119356178092032)

**Comment by aesopwolf** [comment]
This is a good idea, if the goal is to only modify the release text, then I think it would make sense for the `release.js` file to return a function that accepts an object as it's only argument:

```js
// release.js

export default function(release) {
  // release object shape:
  // {
  //   majorChanges: [{
  //     title: '',
  //     description: '',
  //     author: '',
  //     date: '',
  //     hash: ''
  //   }],
  //   minorChanges: [{
  //     // same as above
  //   }],
  //   patches: [{
  //     // same as above
  //   }],
  //   authors: [] // we provide this as a helper even though it's derived data
  // }

  return `
    This release was made possible by the help of:

    ${release.authors.toString()}

    ### Breaking changes
    ... etc.
  `
}
```

**Comment by leo** [comment]
We should not just pass the metadata but also the precompiled text if people just want to replace a certain string with another one.

**Comment by dinoboff** [comment]
I would be happy with config files supporting the definitions of:

- a hook to define each commit type, replacing `release` default filtering. The user is prompted as usually if the hook cannot infer the commit type;
- an async hook (or maybe a template) to render the change list into the release draft body;
- an async hook to run before `release` exits; it would receive the change list and maybe the draft properties.

In addition to local setting config, plugins would be useful 
E.g. a plugin to support angular commit message convention, `release --plugin angular` would  load the settings with `require('release-plugin-angular')`.

**Comment by aesopwolf** [comment]
@dinoboff What are your thoughts on borrowing the lifecycle hooks from react? For example:

```js
export default function() {
  // including `releaseWillReceiveCommit` will automatically disable
  // the built in `release` default filtering
  releaseWillReceiveCommit(commit) {
    /*
      user-land code will go here
      to infer the commit type
    */

    if (/* true: our code above inferred commit type */) {
      return true
    }

    // our code above bombed out so we need to have the CLI ask for the commit type
    return false
  }

  releaseDidReceiveCommit(commit) {
    /*
      user-land code will go here
      to save the commit to memory.
      ie: this.commits[]
    */
  }

  releaseWillExit(props) {
    // props is the same object passed to `render`
    // however, the `body` key will be the user supplied text
  }

  render(props) {
    // props object shape:
    // `majorChanges`, `minorChanges`, and `patches` all come from user
    // filtering if they included `releaseWillReceiveCommit` hook
    // `body` is the default text that `release` generates
    // `authors` is the default list that `release` generates
    // {
    //   majorChanges: [{
    //     title: '',
    //     description: '',
    //     author: '',
    //     date: '',
    //     hash: ''
    //   }],
    //   minorChanges: [{
    //     // same as above
    //   }],
    //   patches: [{
    //     // same as above
    //   }],
    //   body: '', // we provide this in case the user only wants to replace a certain string(s)
    //   authors: [] // we provide this as a helper even though it's derived data
    // }
    return `
      This release was made possible by the help of:

      ${props.authors.toString()}

      ### Breaking changes
      
      ${this.commits.filter((value) => value.breaking).map((commit) => {
        return commit.text
      })}
    `
  }
}

```

**Comment by dinoboff** [comment]
@aesopwolf looking good. Sorry for the late response.

A hook to provide the change list already filtered would be good to. A script bumping the package version using commit, could pass the list of change to `release` via stdin. That hook would parse stdin and provide the list of changes. `release` would then skip commit iteration altogether.

**Comment by aesopwolf** [comment]
> A hook to provide the change list already filtered would be good too.

That would be the `render` function, no? Maybe I'm missing something or misunderstanding.

**Comment by dinoboff** [comment]
@leo The use case would be a version bumper.

1. the plugin would parse the commit from last tag to HEAD instead of release.
1. the plugin would bump the version depending of types of commits.
1. either `release` infer the release version and hash as usual, or the plugin somehow provides the range.
1. the plugin provides the changes list it had to create in the first step.
1. `release` render change list to text.
1. `release` create the github release draft.

**Comment by dinoboff** [comment]
We could have the following actions with hook to before and after those actions.

1. `inferRange`: infer release hash and version, and previous release tag.
1. `validateRange`: check github repo has the release has and previous release tag.
1. `parseLog`: parse logs into change list.
    1. get commit
    1. `processCommit`: transform each commit: define commit type, had extra fields for renderer.
    1. reduce and sort commits.
1. `renderChangelog`: render change list to text.
1. `prepareDraft`: create the release object.
1. `uploadDraft`: upload draft.

Each handlers (plugin/config and default handlers) would be passed a `Release` object

Instead the plugin cancelling the default handler action with a return value, a default handler would just need to check if the data is suppose to set is already set. E.g. the default `parseLog` handler could stop if the `Release` object already has a `changes` property.

```ts
interface Release {
  range:   Range     | null;
  changes: ChangeMap | null;
  draft:   Draft     | null;
}

interface Range {
  release: Tag;
  parent:  Tag;
}

interface Tag {
  tag:       string;
  hasPrefix: boolean;
  hash:      string | null;
}

interface ChangeMap {
  [type: string]: [Commit];
}

interface Commit {
  hash:          string;
  date:          string;
  author:        string;
  type:          type | null;
  [key: string]: any;
}

interface Draft {
  draft:            true;
  tag_name:         string  | null;
  target_commitish: string  | null;
  name:             string  | null;
  body:             string  | null;
  prerelease:       boolean | null;
}
```

**Comment by dinoboff** [comment]
Instead of decorating release flow, a config/plugin could just replace the flow:
```js
'use strict';

const {latestTag, inSync, commits, render} = require('release')
const commitParser = require('some-commit-parser')

/**
 * Prepare release.
 * 
 * @param  {string}   options.pre       Prerelease identifier
 * @param  {boolean}  options.overwrite Overwrite existing release if it exists
 * @param  {string}   options.template  Template to render changes
 * @return {{tag: object, body: string, assets: Array<{path: string, name: string, label: string}>}}
 */
module.exports = async function({template}) {
  const tag = latestTag();
  const changelog = await tag
    .then(inSync())
    .then(commits({mapper: commitParser}))
    .then(render({template}))

  return {
    tag: await tag,
    body: changelog
  }
}
```

**Comment by rauchg** [comment]
For the sake of simplicity, I think it'd be nice if we just get a `data` parameter with all the necessary metadata (`commits`, `authors`, etc), and then return markdown. 

```
export const ({ authors, commits }) => (`
      This release was made possible by the help of:

      ${authors.toString()}

      ### Breaking changes
      
      ${commits.filter((value) => value.breaking).map((commit) => {
        return commit.text
      })}
    `
)
```

I don't think we need lifecycle or complicated async stuff (although the function you export *will* get `await`ed). Thoughts?

**Comment by dinoboff** [comment]
It would allow users to use their own template and to query extra data. You can offer more hooks later.

**Comment by aesopwolf** [comment]
@rauchg I like that, that was pretty much my original proposal.
