### ISSUE TITLE
Don't mention author of release in credits

### ISSUE THREAD

**Issue by leo** [zeit/release#46]

**Comment by Facel3ss1** [comment]
Hi @leo,

I think this would be good, but an alternative could be some sort of `excludeFromCredits` array that excludes certain usernames from the credits. It could be configured using the config file (#38) or somewhere else. This array could include the author of the release, bots etc by default, but the user could add to it for their repo's needs. Regexes could be included as well.

```javascript
let excludeFromCredits = [getReleaseAuthor(), getRepoAuthor(), /[bot]/]

// Then you could check the commits that match the list...
```

It might be best to wait to see if the config file gets implemented, but you could use a CLI flag or `package.json`. What do you think?

**Comment by leo** [comment]
@Facel3ss1 LGTM! But it should work without a flag.

**Comment by leo** [comment]
Closing in favor of https://github.com/zeit/release/issues/77!
