### ISSUE TITLE
GitLab Compatibility (including self-hosted)

### ISSUE THREAD

**Issue by JacobDB** [zeit/release#47]
We use a self-hosted instance of GitLab in my organization. This tool looks great, but sadly I can't use it. Would be awesome if support for GItLab could be added in a future release.

https://about.gitlab.com/

**Comment by leo** [comment]
GitLab is an awesome tool! However, we at @zeit are probably never going to use it. In turn, the push behind supporting this and maintaining the support wouldn't be very good.

I hope you understand... 😊

**Comment by tomevans18** [comment]
@leo before I look into extending Release to support GitLab, would this PR be rejected based on the above comment?
