### ISSUE TITLE
Integration support for management tools (JIRA, Trello, etc.)

### ISSUE THREAD

**Issue by limdauto** [zeit/release#50]
Hey guys, is there a plan to add integration support for management tools such as JIRA, Trello, etc.? We have a mapping between PR & commit with JIRA tickets and it'd be really cool to be able to set the release versions after generating the changelog on those management platforms.

The integration itself is very easy. Was just wondering if you have plan to incorporate them, through a plugin system perhaps?

**Comment by leo** [comment]
No plans, sorry! We'd like to keep the package as minimal as possible.
