### ISSUE TITLE
Two lines before "Credits" section

### ISSUE THREAD

**Issue by leo** [zeit/release#55]
Might only happen under certain conditions. Should be just one! 

<img width="248" alt="screen shot 2017-01-15 at 15 18 09" src="https://cloud.githubusercontent.com/assets/6170607/21963178/056b827c-db36-11e6-86b8-d362cb676028.png">

**Comment by dinoboff** [comment]
Could be easier to avoid issue like by using a template engine and `release` could use the template provided by the repository.
