### ISSUE TITLE
Custom middleware support

### ISSUE THREAD

**Issue by vjeux** [zeit/release#63]
Would be nice to create an image that you can easily share on twitter.

Some things can could be there:
  - The name of the project + version in one line
  - A facepile of all the contributors that helped with the release
  - Generated by `release` so more people know about this

That would be pretty sweet :)

**Comment by rauchg** [comment]
Very cool! 

We're adding support for a custom `release.js` in the workdir, which is going to be "middleware" for the release. Today I also had the use case that some releases I want to automatically upload artifacts, so the signature will probably be

```
release({ commits: [ author, sha, title ], projectData, version }) -> { title, files, desc, version }
```

And in `release.js` you could:
- Invoke the default release desc generator (which is what happens right now)
  - For people who want to release in other languages they can write their own
- Perform side effects (through plugins), like what you're describing

**Comment by leo** [comment]
https://github.com/zeit/release/issues/38
