### ISSUE TITLE
Move commit hash to before commit message

### ISSUE THREAD

**Issue by onbjerg** [zeit/release#67]
Instead of having commit hashes at the end of the commit message like we have now:

![After message](http://i.imgur.com/C409FwF.png)

It would align the changes better if they were before the commit message, since the commit hashes are always the same length:

![Before message](http://i.imgur.com/TAgIkkF.png)

**Comment by onbjerg** [comment]
Probably ties nicely together with #38 but I still think this should be the default

**Comment by leo** [comment]
https://github.com/zeit/release/pull/69#issuecomment-280300168
