### ISSUE TITLE
uploading release fails

### ISSUE THREAD

**Issue by ritz078** [zeit/release#81]
I am always stuck at uploading. 😞 

<img width="290" alt="screen shot 2017-04-10 at 1 13 27 pm" src="https://cloud.githubusercontent.com/assets/5389035/24850941/8c90f0c4-1def-11e7-83ff-12b7d5d54d98.png">

Any help is appreciated.

**Comment by leo** [comment]
We need to add a `--debug` flag for showing additional information.

**Comment by TooTallNate** [comment]
This happened to me just now as well. Was the repo renamed at any point in the past, out of curiosity?

**Comment by ritz078** [comment]
yes

**Comment by leo** [comment]
Ahhh, that's the problem! We don't support redirections yet: https://github.com/zeit/release/issues/64

Thanks @TooTallNate!
