### ISSUE TITLE
Add category named "Dependency Updates"

### ISSUE THREAD

**Issue by leo** [zeit/release#82]
This section should contain all updates made by greenkeeper and filter them out of the list of commits for which a type should be selected.

**Comment by leo** [comment]
[Here](https://github.com/zeit/micro/pull/215)'s an example of such a PR.

**Comment by aesopwolf** [comment]
Why wouldn't a type be selected? Depending on the dependency update wouldn't that affect the parent project in the traditional fashion? Either major, minor, or patch? (Most typically patch).

**Comment by leo** [comment]
This won't be part of the core. But now that `release` supports [hooks](https://github.com/zeit/release#custom-hook), this could be a plugin.
