### ISSUE TITLE
Running for the first time starts at the beginning of the project's commit history

### ISSUE THREAD

**Issue by matthewp** [zeit/release#84]
When running `release` for the first time it starts from the beginning of the repo's commit history and asks the type for each commit. This particular repo has 1500 commits.

This repo already has github releases and tags. Am I doing something wrong? I would think it would start at the last github release and ask about commits since then.

**Comment by leo** [comment]
> I would think it would start at the last github release and ask about commits since then.

That's how it should work. How does a tag look inside your repo, as an example?

**Comment by matthewp** [comment]
Hi @leo, thanks for the reply. [This is the repo](https://github.com/stealjs/steal/releases) in question, as you can see there are release that correspond to a given tag. I think this is typical, right?  I don't have a release for every single tag, is that the problem?

**Comment by leo** [comment]
Looking at the tags, it seems like they're prefixed with "v", I'm not sure if we support that (I think we don't). In turn, it doesn't work correctly.

<img width="81" alt="screen shot 2017-04-13 at 18 16 56" src="https://cloud.githubusercontent.com/assets/6170607/25013832/7725193a-2075-11e7-90b2-2ba33beb776b.png">

[Here](https://github.com/zeit/micro/releases)'s an example of releases without the prefix.

**Comment by matthewp** [comment]
Ah, ok thank you then.
