### ISSUE TITLE
Faster type selection with keyboard shortcuts

### ISSUE THREAD

**Issue by bfred-it** [zeit/release#86]
Instead of up/down arrows, it could allow one-click selection via keyboard:

- <kbd>m</kbd> for major
- <kbd>n</kbd> for minor
- <kbd>p</kbd> for patch
- <kbd>backspace</kbd> for ignore

**Comment by leo** [comment]
That's not possible with [inquirer](https://github.com/SBoudrias/Inquirer.js/), I think. But anyway, you can use the numbers 1-4 for that on your keyboard 😊
