### ISSUE TITLE
Escape HTML

### ISSUE THREAD

**Issue by leo** [zeit/release#91]

**Comment by bfred-it** [comment]
Perhaps with https://github.com/sindresorhus/escape-goat?

**Comment by bfred-it** [comment]
I don't think it's a good idea to use HTML in your commit message. I've never seen that rendered anywhere and it looks awful in GitHub's regular commit list.

I was initially thinking of extended commit messages but those aren't shown anywhere by `release` anyway.

**Comment by hoodwink73** [comment]
So, is it a fair assumption to make – any unclosed HTML tags should be escaped and rest we let it be?

**Comment by hoodwink73** [comment]
Oh! cool. Makes sense.  

Thanks.

**Comment by hoodwink73** [comment]
Just to be explicit about my understanding here. If we have unclosed tags like `h1`, `strong` etc. alike; the rest of the message will be wrapped in them. Hence, we need to escape them.

<img width="928" alt="screenshot 2018-01-12 23 27 14" src="https://user-images.githubusercontent.com/1285699/34888486-7526b5dc-f7f0-11e7-8c95-eca083e3cc7e.png">

<hr />

<img width="604" alt="screenshot 2018-01-12 23 29 09" src="https://user-images.githubusercontent.com/1285699/34888493-7d4224c2-f7f0-11e7-8ed7-dfc638250105.png">

**Comment by bfred-it** [comment]
I think **all** HTML should be escaped because

I don't think it's a good idea to use HTML in your commit message.

**Comment by leo** [comment]
Exactly, I think so too. All HTML should be allowed (e.g. when using the hook), but HTML inside commit messages should be trimmed out.
