### ISSUE TITLE
Possible bug: "release" hangs forever if the github url changes for a project (e.g. project name changes)

### ISSUE THREAD

**Issue by dsifford** [zeit/release#92]
Not sure if this is by design or not.

### How to reproduce
1. Create a repo on github and pull it locally. 
2. Make some commits.
3. Change the name of the repo on github.
4. Make some more commits.
5. Run `release`

Commits will still work because github redirects the old url to the new one, however `release` will hang forever.

**Comment by dsifford** [comment]
Having said that, the user can fix the issue on his/her side as well just by simply either deleting the project and re-pulling from the new url or running `git remote set-url origin <new-origin-url>`

**Comment by leo** [comment]
Duplication of https://github.com/zeit/release/issues/64
