### ISSUE TITLE
Add ability to create tag and push

### ISSUE THREAD

**Issue by leo** [zeit/release#95]
This should automatically increment the version tag in `package.json`, `package-lock.json` and maybe even `app.yaml`... 😊 

Example: `release major`

And make it run `postversion` if that's official.

**Comment by Izhaki** [comment]
Note that you can add this to your `package.json`:

```json
  "scripts": {
    "postversion": "git push && git push --tags && release"
  }
```
Then just run

    npm version major

And get all the magic done.

Having `release` doing what you ask means more functionality (meaning more complexity) and yet another way to do something. Not completely sold by it.

**Comment by leo** [comment]
The problem is that `npm version` prefixes the version with a "v" - we don't do or recommend that.

**Comment by Izhaki** [comment]
I see.

Just out of interest - why?

**Comment by leo** [comment]
Because it's not necessary... 😊
