### ISSUE TITLE
Make 'latest version of node' more specific.

### ISSUE THREAD

**Issue by Izhaki** [zeit/release#97]
The [readme.md](https://github.com/zeit/release/blob/c3cccf37d537881e915ddea36db0571b64dfadc3/readme.md) states:

> (you'll need the latest version of [Node](https://nodejs.org) - [why?](https://github.com/zeit/release/blob/5109c726441f002c969c083029511e406f3cd033/bin/release.js#L2))

Now the latest version of node is rather generic and subject to change.

At the time of writing, the page linked actually shows v8.2.1 as the current version. I have v6.9.5 as my nvm default. Based on the line above - no joy for me.

[package.json](https://github.com/zeit/release/blob/c3cccf37d537881e915ddea36db0571b64dfadc3/package.json), however, has:

```json
  "engines": {
    "node": ">= 6.9.0"
  },
```

So I can only assume this is the actual requirement? It does work with v6.9.5 it seems.

Would be nice to be more specific about the actual version.

**Comment by leo** [comment]
Great idea, thanks!
