### ISSUE TITLE
Changes format in release log can accommodate more commit message styles.

### ISSUE THREAD

**Issue by Izhaki** [zeit/release#98]
If you look at the this [release log](https://github.com/Izhaki/nodemon-webpack-plugin/releases), produced using `release`, you'll see:

> Build: Use XO as linter.: 8ee6397

The thing to note is the `.:`.

Some of us are accustomed to a full stop at the end of the commit message - which stems from adherence to style guides (a sentence shall end with a full stop).

Controversial alright.

I believe `release` can support a more use cases if the instead of adding

    : %commit

It will use:

    (%commit)

So a commit message with a full stop at the end will look like so:

> Build: Use XO as linter. (8ee6397)

That will also play along commit messages without full stop:

> Build: Use XO as linter (8ee6397)

Can submit a PR.

**Comment by leo** [comment]
Commit titles are no sentences, but rather titles. Titles don't end with full stops. However, commit messages are sentences - in turn, full stops are alright there... 😊

**Comment by Izhaki** [comment]
From [Merriam Webster](https://www.merriam-webster.com/dictionary/title):

```text
Definition of title
1
a :  the distinguishing name of a written, printed, or filmed production
b :  a similar distinguishing name of a musical composition or a work of art
2
:  a usually published work as distinguished from a particular copy published 25 new titles
3
:  a descriptive name :  appellation
4
a :  an appellation of dignity, honor, distinction, or preeminence attached to a person or family by virtue of rank, office, precedent, privilege, attainment, or lands
b :  a person holding a title especially of nobility
5
:  championship 1
6
a :  a legally just cause of exclusive possession
b :  the instrument (such as a deed) that is evidence of a right
c :  all the elements constituting legal ownership
7
a :  a descriptive or general heading (as of a chapter in a book)
b :  the heading which names an act or statute
c :  the heading of a legal action or proceeding
8
:  a division of an instrument, book, or bill; especially :  one larger than a section or article
9
a :  something that justifies or substantiates a claim
b :  an alleged or recognized right
10
a :  written material introduced into a motion picture or television program to give credits, explain an action, or represent dialogue —usually used in plural
b obsolete :  inscription
```

As for [sentence](https://www.merriam-webster.com/dictionary/sentence):

```Text
a :  a word, clause, or phrase or a group of clauses or phrases forming a syntactic unit which expresses an assertion, a question, a command, a wish, an exclamation, or the performance of an action, that in writing usually begins with a capital letter and concludes with appropriate end punctuation, and that in speaking is distinguished by characteristic patterns of stress, pitch, and pauses
```

Also, you'd typically classify something as a sentence if it has a verb and a subject.

Looking at your own [commit log](https://github.com/zeit/release/commits/master) you can argue that some of the commit 'titles' are actually sentences.

There's also the idea that requirements should be phrased in active voice, using a verb, and these requirements often end up as commit messages.

----

Having deliberated this endlessly in the past, these are my two cents.

Don't think it is worth continuing the discussion here, as it all a matter of opinions. But I urge you not to take such a binary stance on the matter.
