### ISSUE TITLE
Support CalVer or custom versioning

### ISSUE THREAD

**Issue by kevin940726** [zeit/release#99]
Hi, I really like this project, but our project use a different versioning other than SemVer. Is supporting other versioning part of the feature plan?  Or am I missing something that I can easily do it myself? Thanks for your time! 🙂

**Comment by leo** [comment]
Thanks for the effort you've put into opening this issue, @kevin940726. But we're not planning to support other versioning schemes other than SemVer in the future. It's the most widely used (and in my opinion also the best). I hope you understand! 😊

**Comment by kevin940726** [comment]
Sure! Thanks for your quick reply 👍
